---
cog_bundle_version: 4

name: helper
version: 0.0.4
docker:
  image: cloudbutler/helper
  tag: 0.0.4
description: Interactive help bundle for navigating CloudButler features
author: Joseph Belyeu <github.com/jcbelyeu>
commands:
  architecture:
    executable: /home/bundle/bin/architecture.sh
    description: Get a description of the architecture of CloudButler
    rules:
      - allow
  bundles:
    executable: /home/bundle/bin/bundles.sh
    description: Get description of what bundles are in CloudButler 
    rules:
      - allow
  make-bundle:
    executable: /home/bundle/bin/architecture.sh
    description: Learn more about how architecture is set up in Cloudbutler
    rules:
      - allow
  prebuilt:
    executable: /home/bundle/bin/prebuilt.sh
    description: Links to useful bundles that someone else made for you 
    rules:
      - allow
  add-owner:
    executable: /home/bundle/bin/add-owner.sh
    description: Adds a user to the chatbot owner group.
    rules:
      - allow
    options:
      user:
        description: Specifies the username of the owner to be added.
        type: string
        required: true
        short_flag: u
      password:
        description: Specifies the master password for the chatbot instance.
        type: string
        required: true
        short_flag: p
  source-code:
    executable: /home/bundle/bin/source-code.sh
    description: Find out more about CloudButler from its repo
    rules:
      - allow
  user-groups:
    executable: /home/bundle/bin/user-groups.sh
    description: Learn more about how groups work in CloudButler
    rules:
      - allow
  vocab:
    executable: /home/bundle/bin/vocab.sh
    description: For looking up specific words in the context of CloudButler
    rules:
      - allow
  get-started:
    executable: /home/bundle/bin/start.sh
    description: Quick explanation of how to get started.
    rules:
      - allow
  start: 
    executable: /home/bundle/bin/start.sh
    description: Quick explanation of how to get started.
    rules:
      - allow
  printenv:
    executable: /home/bundle/bin/printenv.sh
    rules:
      - allow
  cogctl:
    executable: /home/bundle/bin/cogctl.sh
    rules:
      - allow
    options:
      password:
        description: Specifies the master password for the chatbot instance.
        type: string
        required: true
        short_flag: p
  eval:
    executable: /home/bundle/bin/eval.sh
    rules:
      - allow
