---
cog_bundle_version: 4

name: helper
version: 0.0.1
docker:
  image: cloudbutler/helper
  tag: 0.0.1
description: Interactive help bundle for navigating CloudButler features
author: Joseph Belyeu <github.com/jcbelyeu>
commands:
  architecture:
    executable: /home/bundle/docs/architecture.sh
    description: Get a description of the architecture of CloudButler
    rules:
      - allow
  bundles:
    executable: /home/bundle/docs/adding-bundles/adding-bundles.sh
    description: Get description of what bundles are in CloudButler 
    rules:
      - allow
  make-bundle:
    executable: /home/bundle/docs/architecture/architecture.sh
    description: Learn more about how architecture is set up in Cloudbutler
    rules:
      - allow
  prebuilt:
    executable: /home/bundle/docs/prebuiltBundles/prebuiltBundles.sh
    description: Links to useful bundles that someone else made for you 
    rules:
      - allow
  add-owner:
    executable: /home/bundle/bin/add-owner.sh
    description: Adds a user to the chatbot owner group.
    rules:
      - allow
    options:
      user:
        description: Specifies the username of the owner to be added.
        type: string
        required: true
        short_flag: u
      password:
        description: Specifies the master password for the chatbot instance.
        type: string
        required: true
        short_flag: p
  source-code:
    executable: /home/bundle/docs/sourceCode/sourceCode.sh
    description: Find out more about CloudButler from its repo
    rules:
      - allow
  user-groups:
    executable: /home/bundle/docs/user-groups/user-groups.sh
    description: Learn more about how groups work in CloudButler
    rules:
      - allow
  vocab:
    executable: /home/bundle/docs/vocab/vocab.sh
    description: For looking up specific words in the context of CloudButler
    rules:
      - allow
